spring:
  datasource:
    url: jdbc:h2:mem:testdb
    initialization-mode: always
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
jwt:
  secret: c3ByaW5nYm9vdC1qd3QtdHV0b3JpYWwtc3ByaW5nYm9vdC1qd3QtdHV0b3JpYWwtc3ByaW5nYm9vdC1qd3QtdHV0b3JpYWwK
  access-token-validity-in-seconds: 64800
  refresh-token-validity-in-seconds: 648000
logging:
  level:
    org.hibernate:
      SQL: debug
      type.descriptor.sql: trace
